version: '3'
services:
    frontend:
        build:
            dockerfile: ./frontend/react.dockerfile
            context: .
        volumes:
            - ./frontend/:/var/www/frontend
            - /var/www/frontend/node_modules
        image: gputrick/react
        container_name: react
        ports:
            - "3000:3000"
        networks: 
            - crawler-network
    backend:
        build:
            dockerfile: ./backend/django.dockerfile
            context: .
        volumes:
            - ./backend/:/var/www/backend
        image: gputrick/django
        container_name: django
        ports:
            - "8000:8000"
        networks: 
            - crawler-network
        depends_on: 
            - database
    database:
        image: postgres:9.6
        container_name: "postgres"
        environment:
            - POSTGRES_DB=crawler
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - TZ=GMT
        volumes:
            - "/var/lib/postgresql/data"
        networks: 
            - crawler-network
networks:
    crawler-network:
        driver: bridge