version: '3'
services:
    frontend:
        build:
            dockerfile: react-dev.dockerfile
            context: ./frontend
        volumes:
            - ./frontend/:/app
            - /app/node_modules
        image: gputrick/react
        container_name: react
        ports:
            - "3000:3000"
    backend:
        build:
            dockerfile: django-dev.dockerfile
            context: ./backend
        volumes:
            - ./backend/:/app
        image: gputrick/django
        container_name: django
        ports:
            - "8000:8000"
        depends_on: 
            - database
    database:
        image: postgres:9.6
        container_name: "postgres"
        environment:
            - POSTGRES_DB=crawler
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - TZ=GMT
        volumes:
            - "/var/lib/postgresql/data"