# Generated by Django 3.0 on 2019-12-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process_number', models.CharField(max_length=255, unique=True)),
                ('kind', models.TextField()),
                ('area', models.TextField()),
                ('subject', models.TextField()),
                ('distribuition', models.TextField()),
                ('judge', models.TextField()),
                ('action_value', models.TextField()),
                ('moves', models.ManyToManyField(to='processsearch.Move')),
            ],
        ),
    ]
