# Generated by Django 3.0 on 2019-12-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.TextField()),
                ('classe', models.TextField()),
                ('subject', models.TextField()),
                ('distribuition', models.TextField()),
                ('control', models.TextField()),
                ('judge', models.TextField()),
                ('action_value', models.TextField()),
            ],
        ),
    ]
