# Generated by Django 3.0 on 2019-12-18 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processsearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('proces', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processsearch.Process')),
            ],
        ),
    ]
