# Generated by Django 3.0 on 2019-12-19 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processsearch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='created_at',
        ),
    ]
