# Generated by Django 3.0 on 2019-12-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processsearch', '0002_remove_process_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('related_people', models.ManyToManyField(to='processsearch.RelatedPeople')),
            ],
        ),
        migrations.AddField(
            model_name='process',
            name='related_parts',
            field=models.ManyToManyField(to='processsearch.RelatedPart'),
        ),
    ]
