# Generated by Django 3.0 on 2019-12-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processsearch', '0002_auto_20191223_0030'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='process',
            index=models.Index(fields=['process_number'], name='processsear_process_7fef8b_idx'),
        ),
    ]
