# Generated by Django 3.0 on 2019-12-18 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processsearch', '0002_move'),
    ]

    operations = [
        migrations.RenameField(
            model_name='move',
            old_name='proces',
            new_name='process',
        ),
    ]
