# Generated by Django 3.0 on 2019-12-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processsearch', '0003_auto_20191219_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedpart',
            name='kind',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
