# Generated by Django 3.0 on 2019-12-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processsearch', '0003_auto_20191218_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='process',
        ),
        migrations.AddField(
            model_name='process',
            name='moves',
            field=models.ManyToManyField(to='processsearch.Move'),
        ),
    ]
