# Generated by Django 3.0 on 2019-12-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processsearch', '0005_auto_20191218_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='process_number',
            field=models.CharField(default=12345, max_length=255),
            preserve_default=False,
        ),
    ]
