# Generated by Django 3.0 on 2019-12-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processsearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='process_number',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
